/**
 * briefImage.ts — render the Daily Brief as a shareable PNG (no external dep,
 * pure Canvas 2D). Portrait 1080×1350 (WhatsApp/Instagram-friendly). The leader
 * can download or native-share it. Client-only (uses document/canvas).
 */

export interface BriefImageData {
  orgName: string;
  scopeLabel: string;
  score: number;
  grade: string;
  accent: string;       // hex
  active: number;
  slaBreached: number;
  filed7: number;
  tasks: string[];
  chiefLine: string;
  dateStr: string;
}

const GRADE_HEX: Record<string, string> = {
  LOW: '#1D9E75', GUARDED: '#639922', ELEVATED: '#BA7517', HIGH: '#D85A30', SEVERE: '#E24B4A',
};

function wrap(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxW: number, lh: number, maxLines = 4): number {
  const words = text.split(/\s+/);
  let line = '';
  let lines = 0;
  for (let i = 0; i < words.length; i++) {
    const test = line ? `${line} ${words[i]}` : words[i];
    if (ctx.measureText(test).width > maxW && line) {
      ctx.fillText(line, x, y);
      line = words[i];
      y += lh;
      if (++lines >= maxLines - 1) {
        let last = line;
        while (ctx.measureText(`${last}…`).width > maxW && last.length) last = last.slice(0, -1);
        ctx.fillText(`${last}…`, x, y);
        return y + lh;
      }
    } else {
      line = test;
    }
  }
  ctx.fillText(line, x, y);
  return y + lh;
}

export async function downloadBriefImage(d: BriefImageData): Promise<void> {
  const W = 1080, H = 1350;
  const canvas = document.createElement('canvas');
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const accent = /^#([0-9a-fA-F]{6})$/.test(d.accent) ? d.accent : '#BA7517';
  const gradeHex = GRADE_HEX[d.grade?.toUpperCase()] || accent;
  const ink = '#0f172a', muted = '#64748b', line = '#e2e8f0';

  // bg
  ctx.fillStyle = '#ffffff'; ctx.fillRect(0, 0, W, H);

  // header band
  ctx.fillStyle = accent; ctx.fillRect(0, 0, W, 210);
  ctx.fillStyle = '#ffffff';
  ctx.font = '600 52px sans-serif'; ctx.textBaseline = 'alphabetic';
  ctx.fillText(d.orgName.slice(0, 30), 64, 96);
  ctx.font = '400 30px sans-serif';
  ctx.fillText('Daily Brief', 64, 145);
  ctx.font = '400 26px sans-serif';
  ctx.globalAlpha = 0.85; ctx.fillText(`${d.scopeLabel} · ${d.dateStr}`, 64, 184); ctx.globalAlpha = 1;

  // risk
  ctx.fillStyle = muted; ctx.font = '400 30px sans-serif';
  ctx.fillText('Risk index', 64, 320);
  ctx.fillStyle = gradeHex; ctx.font = '600 150px sans-serif';
  ctx.fillText(String(d.score), 64, 460);
  ctx.font = '500 40px sans-serif';
  ctx.fillText((d.grade || '').toString(), 320, 440);

  // kpi row
  const kpis = [
    { l: 'Active', v: d.active, c: ink },
    { l: 'SLA breach', v: d.slaBreached, c: '#E24B4A' },
    { l: 'This week', v: d.filed7, c: ink },
  ];
  const colW = (W - 128) / 3;
  ctx.fillStyle = line; ctx.fillRect(64, 520, W - 128, 2);
  kpis.forEach((k, i) => {
    const cx = 64 + i * colW;
    ctx.fillStyle = muted; ctx.font = '400 28px sans-serif'; ctx.fillText(k.l, cx, 600);
    ctx.fillStyle = k.c; ctx.font = '600 72px sans-serif'; ctx.fillText(String(k.v), cx, 678);
  });
  ctx.fillStyle = line; ctx.fillRect(64, 720, W - 128, 2);

  // tasks
  let y = 800;
  ctx.fillStyle = ink; ctx.font = '500 38px sans-serif';
  ctx.fillText("Today's priorities", 64, y); y += 60;
  ctx.font = '400 32px sans-serif';
  if (d.tasks.length) {
    d.tasks.slice(0, 4).forEach((t, i) => {
      ctx.fillStyle = accent; ctx.font = '600 32px sans-serif'; ctx.fillText(`${i + 1}.`, 64, y);
      ctx.fillStyle = ink; ctx.font = '400 32px sans-serif';
      y = wrap(ctx, t, 110, y, W - 174, 44, 2) + 14;
    });
  } else {
    ctx.fillStyle = muted; ctx.fillText('Sab clear — koi pending action nahi.', 64, y); y += 50;
  }

  // chief line
  if (d.chiefLine) {
    y = Math.max(y, 1080);
    ctx.fillStyle = '#f8fafc'; ctx.fillRect(48, y - 44, W - 96, 180);
    ctx.fillStyle = accent; ctx.fillRect(48, y - 44, 8, 180);
    ctx.fillStyle = muted; ctx.font = '500 24px sans-serif'; ctx.fillText('CHIEF-OF-STAFF', 80, y);
    ctx.fillStyle = ink; ctx.font = '400 30px sans-serif';
    wrap(ctx, d.chiefLine, 80, y + 44, W - 176, 40, 3);
  }

  // footer
  ctx.fillStyle = muted; ctx.font = '400 24px sans-serif';
  ctx.fillText('Generated by JanSunwai Intelligence', 64, H - 56);

  const blob: Blob | null = await new Promise((res) => canvas.toBlob(res, 'image/png'));
  if (!blob) return;
  const file = new File([blob], `daily-brief-${d.dateStr.replace(/\s+/g, '-')}.png`, { type: 'image/png' });

  const nav = navigator as Navigator & { canShare?: (d: { files: File[] }) => boolean };
  if (nav.canShare && nav.canShare({ files: [file] })) {
    try { await nav.share({ files: [file], title: `${d.orgName} — Daily Brief` } as ShareData); return; } catch { /* fall through to download */ }
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = file.name;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
