/**
 * CEO Router — n8n Code Node (auto-generated)
 *
 * Generated by: scripts/build-router-code-node.js
 * Source: src/lib/router/ceoRouter.ts
 *
 * This file is self-contained. No require/import — runs in n8n's sandboxed VM.
 * Input: $json.session, $json.message (or $json.parsed)
 * Output: [{ json: { ...$json, ...decision } }]
 */

// ─── Constants ───────────────────────────────────────────────────────────────

const STALE_MS = 30 * 60 * 1000;

const TICKET_RE = /\bWB-\d{4}-\d{5}\b/i;

const KEYWORDS = {
  blood: [
    /\bblood\b/i,
    /\bblod\b/i,
    /\bneed\s+blood\b/i,
    /\b(emergency|sos|urgent)\s+blood\b/i,
    /\bblood\s+(needed|required|request|chahiye|chaahiye|lagbe|please)\b/i,
    /\b(khoon|khun|raqt|rakt|raktt|raktdaata|raktdata)\b/i,
    /\b(khoon|raqt|rakt)\s+(chahiye|chaahiye|ki\s+zaroorat|ki\s+jaroorat)\b/i,
    /\b(rokto|rokta)\s+(lagbe|chai|proyojon|dorkar)\b/i,
    /\bblood\s+lagbe\b/i,
    /\b(a|b|ab|o)\s*[+\-](?=\s|$|[^\w+\-])/i,
    /\b(a|b|ab|o)\s+(positive|negative|pos|neg)\b/i,
    /(रक्त|खून|खुन)/u,
    /(रक्त|खून)\s*(चाहिए|की\s*ज़रूरत|की\s*जरूरत)/u,
    /(রক্ত|খুন|ব্লাড)/u,
    /(রক্ত|খুন|ব্লাড)\s*(লাগবে|প্রয়োজন|চাই|দরকার)/u,
  ],
  donor: [
    /\bdonor\b/i,
    /\bbecome\s+(a\s+)?donor\b/i,
    /\bregister\s+(as\s+)?(a\s+)?donor\b/i,
    /\bi\s+want\s+to\s+donate(\s+blood)?\b/i,
    /\b(blood\s+)?donate\s+blood\b/i,
    /\bdonor\s+(banna|banaa|banna\s+hai|registration|register|ban(na)?\s+chahta)\b/i,
    /\b(blood|raqt|khoon|rakt)\s+donate\s+karna\b/i,
    /\braktdaan\s+(karna|dena|deni|karenge|karunga|karna\s+hai)\b/i,
    /\b(rokto|rokta)\s+(dite|daan|donate)\b/i,
    /\bdonor\s+hote\s+chai\b/i,
    /(रक्तदाता|डोनर|डोनार)/u,
    /(रक्तदान\s*(करना|दूँगा|देंगे|करूँगा|चाहता\s+हूँ|करना\s+है))/u,
    /(डोनर\s*बनना)/u,
    /(ডোনার|ডোনর|রক্তদাতা)/u,
    /(রক্তদান\s*কর(তে|বো|বেন))/u,
    /(দাতা\s*হতে)/u,
  ],
  complaint: [
    /\b(complaint|complaints|grievance|problem|issue)\b/i,
    /\b(road|water|electricity|power|pension|school|college|hostel|scholarship|ration|sewage|drainage|garbage|sanitation|toilet|hospital)\b/i,
    /\bno\s+(water|electricity|power|light)\b/i,
    /\b(road|water|pension|electricity|bijli|pani)\s+(kharab|nahi|broken|repair|cut|band|nai|nei)\b/i,
    /\b(samasya|shikayat|shikaayat|sikayat|pareshani|abhijog)\b/i,
    /\b(sadak|sarak|rasta|paani|pani|bijli|bijlee|skool|skul|skole|raashan|chhatravritti|panchayat)\b/i,
    /\b(rasta|sadak|paani|pani|bijli|pension|raashan|ration|scholarship|skool)\s+(nahi|kharab|band|nai|nei|tuti)\b/i,
    /\b(rasta\s+kharap|jol\s+nei|biduyat\s+nei|abhijog|sikkha)\b/i,
    /(समस्या|शिकायत|परेशानी)/u,
    /(सड़क|पानी|बिजली|पेंशन|स्कूल|राशन|छात्रवृत्ति|शौचालय)/u,
    /(সমস্যা|অভিযোগ)/u,
    /(রাস্তা|জল|পানি|বিদ্যুৎ|পেনশন|স্কুল|রেশন|বৃত্তি|শৌচাগার)/u,
    /(রাস্তা|জল|বিদ্যুৎ|পানি)\s*(খারাপ|নেই|নাই)/u,
  ],
  greeting: [
    /^(hi+|hii+|hello+|helo+|hey+|hai+|hola)[!.,\s]*$/i,
    /^(namaste|namaskar|namaskaar|namashkar|namashkaar|pranam|salaam|salam|adab|aadab)[!.,\s]*$/i,
    /^good\s+(morning|evening|afternoon|night)[!.,\s]*$/i,
    /^(নমস্কার|হ্যালো|হাই|নমস্তে|আদাব|সালাম)[!.,\s]*$/u,
    /^(नमस्ते|नमस्कार|हैलो|प्रणाम|आदाब|सलाम)[!.,\s]*$/u,
  ],
};

// ─── Helper ──────────────────────────────────────────────────────────────────

function matchAny(text, patterns) {
  for (const re of patterns) {
    if (re.test(text)) return true;
  }
  return false;
}

// ─── Core Decision Function ──────────────────────────────────────────────────

function decide(session, message, now) {
  if (!now) now = new Date();
  const rulesEvaluated = [];
  const text = (message.text || '').trim();
  const original = message.original_text || message.text || '';

  let lastIntent = (session && session.last_intent) || 'idle';
  const lastActivityMs = (session && session.last_activity_at)
    ? new Date(session.last_activity_at).getTime()
    : 0;

  // Rule 1: defensive stale belt
  rulesEvaluated.push('stale_belt');
  if (
    lastActivityMs &&
    now.getTime() - lastActivityMs > STALE_MS &&
    lastIntent !== 'idle'
  ) {
    lastIntent = 'idle';
  }

  // Rule 2: explicit state lock
  rulesEvaluated.push('state_lock');
  if (lastIntent === 'donor_pending_response') {
    return { agent: 'blood', reason: 'state:donor_pending_response', rulesEvaluated: rulesEvaluated };
  }
  if (lastIntent === 'seeker_confirming') {
    return { agent: 'blood', reason: 'state:seeker_confirming', rulesEvaluated: rulesEvaluated };
  }

  // Rule 3: state prefix dispatch
  rulesEvaluated.push('state_prefix');
  if (lastIntent.startsWith('complaint_')) {
    return { agent: 'complaint', reason: 'state_prefix:' + lastIntent, rulesEvaluated: rulesEvaluated };
  }
  if (lastIntent.startsWith('blood_')) {
    return { agent: 'blood', reason: 'state_prefix:' + lastIntent, rulesEvaluated: rulesEvaluated };
  }
  if (lastIntent.startsWith('donor_')) {
    return { agent: 'donor', reason: 'state_prefix:' + lastIntent, rulesEvaluated: rulesEvaluated };
  }

  // Rule 4: ticket regex on original text
  rulesEvaluated.push('ticket_regex');
  if (TICKET_RE.test(original)) {
    return { agent: 'info', reason: 'ticket_pattern_detected', rulesEvaluated: rulesEvaluated };
  }

  // Rule 5: greeting on idle → welcome
  rulesEvaluated.push('greeting_idle');
  if (matchAny(text, KEYWORDS.greeting)) {
    return { agent: 'welcome', reason: 'greeting_on_idle', rulesEvaluated: rulesEvaluated };
  }

  // Rule 6: idle keyword routing — blood → donor → complaint
  rulesEvaluated.push('idle_keyword_blood');
  if (matchAny(text, KEYWORDS.blood)) {
    return { agent: 'blood', reason: 'idle_keyword:blood', rulesEvaluated: rulesEvaluated };
  }
  rulesEvaluated.push('idle_keyword_donor');
  if (matchAny(text, KEYWORDS.donor)) {
    return { agent: 'donor', reason: 'idle_keyword:donor', rulesEvaluated: rulesEvaluated };
  }
  rulesEvaluated.push('idle_keyword_complaint');
  if (matchAny(text, KEYWORDS.complaint)) {
    return { agent: 'complaint', reason: 'idle_keyword:complaint', rulesEvaluated: rulesEvaluated };
  }

  // Rule 7: default fallback
  rulesEvaluated.push('default_fallback');
  return { agent: 'welcome', reason: 'unknown_no_state', rulesEvaluated: rulesEvaluated };
}

// ─── n8n Code Node Entry Point ───────────────────────────────────────────────
// $json is the input item from the previous node (Prepare Context).
// Expected shape: { session: { last_intent, last_activity_at, language }, message: { text, original_text }, ... }

const session = $json.session || {};
const message = $json.message || $json.parsed || {};

const decision = decide(session, message);

return [{ json: { ...$json, ...decision } }];
